apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodeapp
spec:
    replicas: 3
    selector:
        matchLabels:
            name: nodeapp
    template:
        metadata:
            labels:
                name: nodeapp
        spec:
            containers:
                - name: nodeapp
                  image: vforv/simple-app-kube:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 3000
