apiVersion: v1
kind: Service
metadata:
    name: nodeapp
spec:
    ports:
       - port: 80
         targetPort: 3000
         protocol: TCP
    selector:
         name: nodeapp
    type: LoadBalancer