version: 2
jobs:
  deploy:
    docker:
      - image: vforv/np:v1
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t simple-node:$TAG .
            docker tag simple-node:$TAG registry.hefest.io/simple-node
            docker login -u $DOCKER_KUBE_USER -p $DOCKER_KUBE_PASS registry.hefest.io
            docker push registry.hefest.io/simple-node
          
            ssh -oStrictHostKeyChecking=no -v $VPS_USER@$VPS_IP bash '
            kubectl -n nodeapp create secret docker-registry regcred \
              --docker-server=registry.hefest.io \
              --docker-username=${DOCKER_USER} \
              --docker-password=${DOCKER_PASS} \
              --docker-email=vladimirdjukic90@gmail.com
            helm upgrade --install nodeapp --set appName=nodeapp --set appImage=registry.hefest.io/simple-node ./kube/manifests
            '
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - deploy:
          context: org-global
          filters:
            branches:
              only:
              - master